name: manowa_apps
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_conditional_rendering: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  lottie: ^2.7.0
  motion_toast: ^2.7.9
  photo_view: ^0.14.0
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - assets/music/
    - assets/lottie/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Charm
      fonts:
        - asset: assets/fonts/Charm/Charm-Regular.ttf
          weight: 300
        - asset: assets/fonts/Charm/Charm-Regular.ttf
          weight: 400
        - asset: assets/fonts/Charm/Charm-Regular.ttf
          weight: 500
        - asset: assets/fonts/Charm/Charm-Bold.ttf
          weight: 600
        - asset: assets/fonts/Charm/Charm-Bold.ttf
          weight: 700
        - asset: assets/fonts/Charm/Charm-Bold.ttf
          weight: 800
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: CormorantUpgright
      fonts:
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Light.ttf
          weight: 300
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cormorant_Upright/CormorantUpright-Bold.ttf
          weight: 800
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 300
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 400
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 500
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 600
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 700
        - asset: assets/fonts/PoetsenOne/PoetsenOne-Regular.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
